### ISSUE TITLE
Add a time-restricted mode in the game

### ISSUE THREAD

**Issue by sriyash421** [sriyash421/Arcus#7]

**Comment by sriyash421** [comment]
A mode with the objective to hit as many balloons as possible in the given time limit(say 60 seconds).

**Comment by Rits1272** [comment]
Can I work on this issue?

**Comment by jay24rajput** [comment]
Hey! Is this issue up for grabs???

**Comment by sriyash421** [comment]
Sorry, this issue has been resolved.
